ryan = User.create(name: "Ryan", img: "https://ultimatemotorcycling.com/wp-content/uploads/2017/05/2017-nicky-hayden-cycling-crash-1.jpg", about: "I've been riding for about 6 years and goes to the occasional trackday. I would like to expand my riding to racing someday.", location: "San Francisco, CA", what_do_you_ride: "2008 Aprilia Tuono Factory", email: "ryan@ryan.com", username: "motomoto")


tailgate = Event.create(name: "Pre-race Party", race: "America GP", date: "9/22/18", location: "Parking Lot B by West Entrance", what_to_bring: "Bring anything you would like grilled!")

Rider.find_by(id: 1).update(img: "https://motogp.hondaracingcorporation.com/wp-content/uploads/sites/3/2014/09/5a805b82531404.34132697.jpg")
Rider.find_by(id: 2).update(img: "https://cdn-6.motorsport.com/static/img/mgl/2500000/2540000/2549000/2549600/2549684/s8/motogp-ducati-desmosedici-gp15-launch-2015-andrea-dovizioso-ducati-team.jpg")
Rider.find_by(id: 3).update(img: "http://www.bikesrepublic.com/wp-content/uploads/2018/01/2018-Movistar-Yamaha-MotoGP-Yamaha-YZR-M1-Maverick-Vinales-Valentino-Rossi_25.jpg")
Rider.find_by(id: 4).update(img: "https://cdn-8.motorsport.com/images/mgl/0R5p4qv6/s8/motogp-team-ducati-launch-2018-jorge-lorenzo-ducati-team.jpg")
Rider.find_by(id: 5).update(img: "https://cdn-9.motorsport.com/images/mgl/6AzLJ7E0/s8/motogp-yamaha-team-launch-2018-maverick-vinales-yamaha-factory-racing.jpg")
Rider.find_by(id: 6).update(img: "https://rtrsports.co.uk/wp-content/uploads/2017/03/lcr_1.jpg")
Rider.find_by(id: 7).update(img: "https://d2d0b2rxqzh1q5.cloudfront.net/sv/2.183/dir/647/image/647a030c272db50e6d7fb10090911b71.jpg")
Rider.find_by(id: 8).update(img: "http://bikenationmag.com/wp-content/uploads/2018/06/ab74579f.jpg")
Rider.find_by(id: 9).update(img: "https://cdn-5.motorsport.com/images/mgl/2QvzJpWY/s8/motogp-suzuki-motogp-2017-launch-2017-andrea-iannone-team-suzuki-ecstar-motogp.jpg")
Rider.find_by(id: 10).update(img: "https://www.crash.net/sites/default/files/styles/article/public/image_importer/MotoGP/gg722476.jpg")
Rider.find_by(id: 11).update(img: "https://cdn.drivemag.net/media/default/0001/85/Dani-Pedrosa-6455-default-large.jpeg")
Rider.find_by(id: 12).update(img: "https://i0.wp.com/www.asphaltandrubber.com/wp-content/uploads/2015/03/2015-Aprilia-RS-GP-Alvaro-Bautista-07.jpg")
Rider.find_by(id: 13).update(img: "https://ultimatemotorcycling.com/wp-content/uploads/2017/10/2017-jack-miller-breaks-right-foot-to-miss-motegi-motogp.jpg")
Rider.find_by(id: 14).update(img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Esteve_Rabat_Moto2-2015_%282%29.JPG/1200px-Esteve_Rabat_Moto2-2015_%282%29.jpg")
Rider.find_by(id: 15).update(img: "http://www.polespargaro.com/img/Pol-Espargaro-Losail-2017-01.jpg")
Rider.find_by(id: 16).update(img: "https://cdn-5.motorsport.com/images/mgl/0kPA5LV2/s8/moto2-valencia-2016-franco-morbidelli-marc-vds.jpg")
Rider.find_by(id: 17).update(img: "http://i-moto.com.my/wp-content/uploads/2017/02/55-hafizh-syahrin-mal_gp_3060.gallery_full_top_md.jpg")
Rider.find_by(id: 18).update(img: "https://img-z.okeinfo.net/library/images/2018/04/23/2cqrq23hy1ibr1od36xg_18030.jpg")
Rider.find_by(id: 19).update(img: "http://www.oxfordmail.co.uk/resources/images/7070514.jpg")
Rider.find_by(id: 20).update(img: "https://global.honda/content/dam/site/global/motorsports/cq_img/motogp/2018/riders-closeup/takaaki-nakagami/main.jpg")
Rider.find_by(id: 21).update(img: "http://www.aprilia.com/assets/aprilia-racing/motoGp/riders/redding/2018/redding_headrer_2018/original/redding_headrer_2018.jpg")
Rider.find_by(id: 22).update(img: "https://cdn-8.motorsport.com/images/mgl/6gnBvdbY/s8/motogp-valencia-gp-2016-mika-kallio-red-bull-ktm-factory-racing.jpg")
Rider.find_by(id: 23).update(img: "https://www.karelabraham.com/media/image/mugello_sob_ab-cardion_teamfoto-102.jpg")
Rider.find_by(id: 24).update(img: "https://www.sportrider.com/sites/sportrider.com/files/styles/1000_1x_/public/16pirro-1.jpg")
Rider.find_by(id: 25).update(img: "http://photos.motogp.com/2016/09/05/12-thomas-luthi-sui_gp_9917.big.jpg")
Rider.find_by(id: 26).update(img: "https://cdn-1.motorsport.com/images/mgl/0RB8elA0/s8/motogp-presentation-aprillia-racing-gresini-racing-2016-stefan-bradl-gresini-racing-april.jpg")
Rider.find_by(id: 27).update(img: "https://www.crash.net/sites/default/files/styles/article/public/image_importer/MotoGP/690977.jpg")
Rider.find_by(id: 28).update(img: "http://www.motorcycle-usa.com/wp-content/uploads/2013/11/Sylvain-Guintoli.jpg")
Rider.find_by(id: 29).update(img: "http://photos.worldsbk.com/2014/12/12/christophe-ponssonjpg_full.jpg")
